-- USER SQL
CREATE USER "C##BD_AMAZON" IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "C##BD_AMAZON" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "C##BD_AMAZON" ;
GRANT "RESOURCE" TO "C##BD_AMAZON" ;

-- SYSTEM PRIVILEGES
GRANT CREATE MATERIALIZED VIEW TO "C##BD_AMAZON" ;
GRANT CREATE VIEW TO "C##BD_AMAZON" ;
GRANT CREATE TABLE TO "C##BD_AMAZON" ;
GRANT CREATE TYPE TO "C##BD_AMAZON" ;
GRANT CREATE SEQUENCE TO "C##BD_AMAZON" ;
